package db_mapping_files;
// Generated Feb 23, 2018 2:08:47 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TbAddressInfo generated by hbm2java
 */
@Entity
@Table(name="tb_address_info"
    ,catalog="safenets_epacs"
)
public class TbAddressInfo  implements java.io.Serializable {


     private Integer aiId;
     private TbCustomerInfo tbCustomerInfo;
     private String aiPostalCode;
     private String aiPrefecture;
     private String aiCityDistrictTown;
     private String aiAddressTwo;
     private String aiLastUpdate;
     private String aiStatus;

    public TbAddressInfo() {
    }

	
    public TbAddressInfo(TbCustomerInfo tbCustomerInfo) {
        this.tbCustomerInfo = tbCustomerInfo;
    }
    public TbAddressInfo(TbCustomerInfo tbCustomerInfo, String aiPostalCode, String aiPrefecture, String aiCityDistrictTown, String aiAddressTwo, String aiLastUpdate, String aiStatus) {
       this.tbCustomerInfo = tbCustomerInfo;
       this.aiPostalCode = aiPostalCode;
       this.aiPrefecture = aiPrefecture;
       this.aiCityDistrictTown = aiCityDistrictTown;
       this.aiAddressTwo = aiAddressTwo;
       this.aiLastUpdate = aiLastUpdate;
       this.aiStatus = aiStatus;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ai_id", unique=true, nullable=false)
    public Integer getAiId() {
        return this.aiId;
    }
    
    public void setAiId(Integer aiId) {
        this.aiId = aiId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="tb_customer_info_ci_id", nullable=false)
    public TbCustomerInfo getTbCustomerInfo() {
        return this.tbCustomerInfo;
    }
    
    public void setTbCustomerInfo(TbCustomerInfo tbCustomerInfo) {
        this.tbCustomerInfo = tbCustomerInfo;
    }

    
    @Column(name="ai_postal_code", length=45)
    public String getAiPostalCode() {
        return this.aiPostalCode;
    }
    
    public void setAiPostalCode(String aiPostalCode) {
        this.aiPostalCode = aiPostalCode;
    }

    
    @Column(name="ai_prefecture", length=100)
    public String getAiPrefecture() {
        return this.aiPrefecture;
    }
    
    public void setAiPrefecture(String aiPrefecture) {
        this.aiPrefecture = aiPrefecture;
    }

    
    @Column(name="ai_city_district_town", length=100)
    public String getAiCityDistrictTown() {
        return this.aiCityDistrictTown;
    }
    
    public void setAiCityDistrictTown(String aiCityDistrictTown) {
        this.aiCityDistrictTown = aiCityDistrictTown;
    }

    
    @Column(name="ai_address_two")
    public String getAiAddressTwo() {
        return this.aiAddressTwo;
    }
    
    public void setAiAddressTwo(String aiAddressTwo) {
        this.aiAddressTwo = aiAddressTwo;
    }

    
    @Column(name="ai_last_update", length=45)
    public String getAiLastUpdate() {
        return this.aiLastUpdate;
    }
    
    public void setAiLastUpdate(String aiLastUpdate) {
        this.aiLastUpdate = aiLastUpdate;
    }

    
    @Column(name="ai_status", length=45)
    public String getAiStatus() {
        return this.aiStatus;
    }
    
    public void setAiStatus(String aiStatus) {
        this.aiStatus = aiStatus;
    }




}


