package db_mapping_files;
// Generated Feb 21, 2018 1:25:15 AM by Hibernate Tools 4.3.1



/**
 * TbBasicInfo generated by hbm2java
 */
public class TbBasicInfo  implements java.io.Serializable {


     private Integer biId;
     private TbUserAccount tbUserAccount;
     private String biFirstName;
     private String biLastName;
     private String biJapanName;
     private String biStatus;

    public TbBasicInfo() {
    }

	
    public TbBasicInfo(TbUserAccount tbUserAccount) {
        this.tbUserAccount = tbUserAccount;
    }
    public TbBasicInfo(TbUserAccount tbUserAccount, String biFirstName, String biLastName, String biJapanName, String biStatus) {
       this.tbUserAccount = tbUserAccount;
       this.biFirstName = biFirstName;
       this.biLastName = biLastName;
       this.biJapanName = biJapanName;
       this.biStatus = biStatus;
    }
   
    public Integer getBiId() {
        return this.biId;
    }
    
    public void setBiId(Integer biId) {
        this.biId = biId;
    }
    public TbUserAccount getTbUserAccount() {
        return this.tbUserAccount;
    }
    
    public void setTbUserAccount(TbUserAccount tbUserAccount) {
        this.tbUserAccount = tbUserAccount;
    }
    public String getBiFirstName() {
        return this.biFirstName;
    }
    
    public void setBiFirstName(String biFirstName) {
        this.biFirstName = biFirstName;
    }
    public String getBiLastName() {
        return this.biLastName;
    }
    
    public void setBiLastName(String biLastName) {
        this.biLastName = biLastName;
    }
    public String getBiJapanName() {
        return this.biJapanName;
    }
    
    public void setBiJapanName(String biJapanName) {
        this.biJapanName = biJapanName;
    }
    public String getBiStatus() {
        return this.biStatus;
    }
    
    public void setBiStatus(String biStatus) {
        this.biStatus = biStatus;
    }




}


