package db_mapping_files;
// Generated Feb 23, 2018 2:08:47 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TbCartInfo generated by hbm2java
 */
@Entity
@Table(name="tb_cart_info"
    ,catalog="safenets_epacs"
)
public class TbCartInfo  implements java.io.Serializable {


     private Integer ciId;
     private TbProductInfo tbProductInfo;
     private String ciStatus;
     private Set<TbCartRegister> tbCartRegisters = new HashSet<TbCartRegister>(0);

    public TbCartInfo() {
    }

	
    public TbCartInfo(TbProductInfo tbProductInfo) {
        this.tbProductInfo = tbProductInfo;
    }
    public TbCartInfo(TbProductInfo tbProductInfo, String ciStatus, Set<TbCartRegister> tbCartRegisters) {
       this.tbProductInfo = tbProductInfo;
       this.ciStatus = ciStatus;
       this.tbCartRegisters = tbCartRegisters;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ci_id", unique=true, nullable=false)
    public Integer getCiId() {
        return this.ciId;
    }
    
    public void setCiId(Integer ciId) {
        this.ciId = ciId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="tb_product_info_pi_id", nullable=false)
    public TbProductInfo getTbProductInfo() {
        return this.tbProductInfo;
    }
    
    public void setTbProductInfo(TbProductInfo tbProductInfo) {
        this.tbProductInfo = tbProductInfo;
    }

    
    @Column(name="ci_status", length=45)
    public String getCiStatus() {
        return this.ciStatus;
    }
    
    public void setCiStatus(String ciStatus) {
        this.ciStatus = ciStatus;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tbCartInfo")
    public Set<TbCartRegister> getTbCartRegisters() {
        return this.tbCartRegisters;
    }
    
    public void setTbCartRegisters(Set<TbCartRegister> tbCartRegisters) {
        this.tbCartRegisters = tbCartRegisters;
    }




}


