package db_mapping_files;
// Generated Feb 20, 2018 3:38:57 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TbCatagoryInfo generated by hbm2java
 */
public class TbCatagoryInfo  implements java.io.Serializable {


     private Integer ciId;
     private String ciTitle;
     private String ciStatus;
     private Set<TbSubcatagoryInfo> tbSubcatagoryInfos = new HashSet<TbSubcatagoryInfo>(0);

    public TbCatagoryInfo() {
    }

    public TbCatagoryInfo(String ciTitle, String ciStatus, Set<TbSubcatagoryInfo> tbSubcatagoryInfos) {
       this.ciTitle = ciTitle;
       this.ciStatus = ciStatus;
       this.tbSubcatagoryInfos = tbSubcatagoryInfos;
    }
   
    public Integer getCiId() {
        return this.ciId;
    }
    
    public void setCiId(Integer ciId) {
        this.ciId = ciId;
    }
    public String getCiTitle() {
        return this.ciTitle;
    }
    
    public void setCiTitle(String ciTitle) {
        this.ciTitle = ciTitle;
    }
    public String getCiStatus() {
        return this.ciStatus;
    }
    
    public void setCiStatus(String ciStatus) {
        this.ciStatus = ciStatus;
    }
    public Set<TbSubcatagoryInfo> getTbSubcatagoryInfos() {
        return this.tbSubcatagoryInfos;
    }
    
    public void setTbSubcatagoryInfos(Set<TbSubcatagoryInfo> tbSubcatagoryInfos) {
        this.tbSubcatagoryInfos = tbSubcatagoryInfos;
    }




}


