package db_mapping_files;
// Generated Feb 23, 2018 2:08:47 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TbCartRegister generated by hbm2java
 */
@Entity
@Table(name="tb_cart_register"
    ,catalog="safenets_epacs"
)
public class TbCartRegister  implements java.io.Serializable {


     private Integer crId;
     private TbCartInfo tbCartInfo;

    public TbCartRegister() {
    }

    public TbCartRegister(TbCartInfo tbCartInfo) {
       this.tbCartInfo = tbCartInfo;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="cr_id", unique=true, nullable=false)
    public Integer getCrId() {
        return this.crId;
    }
    
    public void setCrId(Integer crId) {
        this.crId = crId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="tb_cart_info_ci_id", nullable=false)
    public TbCartInfo getTbCartInfo() {
        return this.tbCartInfo;
    }
    
    public void setTbCartInfo(TbCartInfo tbCartInfo) {
        this.tbCartInfo = tbCartInfo;
    }




}


