package db_mapping_files;
// Generated Feb 23, 2018 2:08:47 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TbCustomerInfo generated by hbm2java
 */
@Entity
@Table(name="tb_customer_info"
    ,catalog="safenets_epacs"
)
public class TbCustomerInfo  implements java.io.Serializable {


     private Integer ciId;
     private String ciFirstName;
     private String ciLastName;
     private String ciContactNo;
     private String ciRegisterDate;
     private String ciLastUpdateDate;
     private String ciStatus;
     private Set<TbAddressInfo> tbAddressInfos = new HashSet<TbAddressInfo>(0);

    public TbCustomerInfo() {
    }

    public TbCustomerInfo(String ciFirstName, String ciLastName, String ciContactNo, String ciRegisterDate, String ciLastUpdateDate, String ciStatus, Set<TbAddressInfo> tbAddressInfos) {
       this.ciFirstName = ciFirstName;
       this.ciLastName = ciLastName;
       this.ciContactNo = ciContactNo;
       this.ciRegisterDate = ciRegisterDate;
       this.ciLastUpdateDate = ciLastUpdateDate;
       this.ciStatus = ciStatus;
       this.tbAddressInfos = tbAddressInfos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ci_id", unique=true, nullable=false)
    public Integer getCiId() {
        return this.ciId;
    }
    
    public void setCiId(Integer ciId) {
        this.ciId = ciId;
    }

    
    @Column(name="ci_first_name", length=45)
    public String getCiFirstName() {
        return this.ciFirstName;
    }
    
    public void setCiFirstName(String ciFirstName) {
        this.ciFirstName = ciFirstName;
    }

    
    @Column(name="ci_last_name", length=45)
    public String getCiLastName() {
        return this.ciLastName;
    }
    
    public void setCiLastName(String ciLastName) {
        this.ciLastName = ciLastName;
    }

    
    @Column(name="ci_contact_no", length=45)
    public String getCiContactNo() {
        return this.ciContactNo;
    }
    
    public void setCiContactNo(String ciContactNo) {
        this.ciContactNo = ciContactNo;
    }

    
    @Column(name="ci_register_date", length=45)
    public String getCiRegisterDate() {
        return this.ciRegisterDate;
    }
    
    public void setCiRegisterDate(String ciRegisterDate) {
        this.ciRegisterDate = ciRegisterDate;
    }

    
    @Column(name="ci_last_update_date", length=45)
    public String getCiLastUpdateDate() {
        return this.ciLastUpdateDate;
    }
    
    public void setCiLastUpdateDate(String ciLastUpdateDate) {
        this.ciLastUpdateDate = ciLastUpdateDate;
    }

    
    @Column(name="ci_status", length=45)
    public String getCiStatus() {
        return this.ciStatus;
    }
    
    public void setCiStatus(String ciStatus) {
        this.ciStatus = ciStatus;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tbCustomerInfo")
    public Set<TbAddressInfo> getTbAddressInfos() {
        return this.tbAddressInfos;
    }
    
    public void setTbAddressInfos(Set<TbAddressInfo> tbAddressInfos) {
        this.tbAddressInfos = tbAddressInfos;
    }




}


