package db_mapping_files;
// Generated Feb 21, 2018 1:25:15 AM by Hibernate Tools 4.3.1



/**
 * TbDateTime generated by hbm2java
 */
public class TbDateTime  implements java.io.Serializable {


     private Integer dtId;
     private String dtDateText;
     private String dtStatus;

    public TbDateTime() {
    }

    public TbDateTime(String dtDateText, String dtStatus) {
       this.dtDateText = dtDateText;
       this.dtStatus = dtStatus;
    }
   
    public Integer getDtId() {
        return this.dtId;
    }
    
    public void setDtId(Integer dtId) {
        this.dtId = dtId;
    }
    public String getDtDateText() {
        return this.dtDateText;
    }
    
    public void setDtDateText(String dtDateText) {
        this.dtDateText = dtDateText;
    }
    public String getDtStatus() {
        return this.dtStatus;
    }
    
    public void setDtStatus(String dtStatus) {
        this.dtStatus = dtStatus;
    }




}


