package db_mapping_files;
// Generated Feb 20, 2018 3:38:57 PM by Hibernate Tools 4.3.1



/**
 * TbImagesInfo generated by hbm2java
 */
public class TbImagesInfo  implements java.io.Serializable {


     private Integer iiId;
     private TbProductInfo tbProductInfo;
     private String iiPath;
     private String iiStatus;

    public TbImagesInfo() {
    }

	
    public TbImagesInfo(TbProductInfo tbProductInfo) {
        this.tbProductInfo = tbProductInfo;
    }
    public TbImagesInfo(TbProductInfo tbProductInfo, String iiPath, String iiStatus) {
       this.tbProductInfo = tbProductInfo;
       this.iiPath = iiPath;
       this.iiStatus = iiStatus;
    }
   
    public Integer getIiId() {
        return this.iiId;
    }
    
    public void setIiId(Integer iiId) {
        this.iiId = iiId;
    }
    public TbProductInfo getTbProductInfo() {
        return this.tbProductInfo;
    }
    
    public void setTbProductInfo(TbProductInfo tbProductInfo) {
        this.tbProductInfo = tbProductInfo;
    }
    public String getIiPath() {
        return this.iiPath;
    }
    
    public void setIiPath(String iiPath) {
        this.iiPath = iiPath;
    }
    public String getIiStatus() {
        return this.iiStatus;
    }
    
    public void setIiStatus(String iiStatus) {
        this.iiStatus = iiStatus;
    }




}


