package db_mapping_files;
// Generated Feb 23, 2018 2:08:47 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TbInvoiceInfo generated by hbm2java
 */
@Entity
@Table(name="tb_invoice_info"
    ,catalog="safenets_epacs"
)
public class TbInvoiceInfo  implements java.io.Serializable {


     private Integer iiId;
     private TbOrderInfo tbOrderInfo;
     private String iiGenId;
     private Set<TbInvoiceRegister> tbInvoiceRegisters = new HashSet<TbInvoiceRegister>(0);

    public TbInvoiceInfo() {
    }

	
    public TbInvoiceInfo(TbOrderInfo tbOrderInfo) {
        this.tbOrderInfo = tbOrderInfo;
    }
    public TbInvoiceInfo(TbOrderInfo tbOrderInfo, String iiGenId, Set<TbInvoiceRegister> tbInvoiceRegisters) {
       this.tbOrderInfo = tbOrderInfo;
       this.iiGenId = iiGenId;
       this.tbInvoiceRegisters = tbInvoiceRegisters;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ii_id", unique=true, nullable=false)
    public Integer getIiId() {
        return this.iiId;
    }
    
    public void setIiId(Integer iiId) {
        this.iiId = iiId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="tb_order_info_oi_id", nullable=false)
    public TbOrderInfo getTbOrderInfo() {
        return this.tbOrderInfo;
    }
    
    public void setTbOrderInfo(TbOrderInfo tbOrderInfo) {
        this.tbOrderInfo = tbOrderInfo;
    }

    
    @Column(name="ii_gen_id", length=45)
    public String getIiGenId() {
        return this.iiGenId;
    }
    
    public void setIiGenId(String iiGenId) {
        this.iiGenId = iiGenId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tbInvoiceInfo")
    public Set<TbInvoiceRegister> getTbInvoiceRegisters() {
        return this.tbInvoiceRegisters;
    }
    
    public void setTbInvoiceRegisters(Set<TbInvoiceRegister> tbInvoiceRegisters) {
        this.tbInvoiceRegisters = tbInvoiceRegisters;
    }




}


