package db_mapping_files;
// Generated Feb 23, 2018 2:08:47 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TbInvoiceRegister generated by hbm2java
 */
@Entity
@Table(name="tb_invoice_register"
    ,catalog="safenets_epacs"
)
public class TbInvoiceRegister  implements java.io.Serializable {


     private Integer irId;
     private TbInvoiceInfo tbInvoiceInfo;

    public TbInvoiceRegister() {
    }

    public TbInvoiceRegister(TbInvoiceInfo tbInvoiceInfo) {
       this.tbInvoiceInfo = tbInvoiceInfo;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ir_id", unique=true, nullable=false)
    public Integer getIrId() {
        return this.irId;
    }
    
    public void setIrId(Integer irId) {
        this.irId = irId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="tb_invoice_info_ii_id", nullable=false)
    public TbInvoiceInfo getTbInvoiceInfo() {
        return this.tbInvoiceInfo;
    }
    
    public void setTbInvoiceInfo(TbInvoiceInfo tbInvoiceInfo) {
        this.tbInvoiceInfo = tbInvoiceInfo;
    }




}


