package db_mapping_files;
// Generated Feb 23, 2018 2:08:47 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TbOrderStatus generated by hbm2java
 */
@Entity
@Table(name="tb_order_status"
    ,catalog="safenets_epacs"
)
public class TbOrderStatus  implements java.io.Serializable {


     private Integer osId;
     private String osTitle;
     private String osStatus;
     private Set<TbOrderInfo> tbOrderInfos = new HashSet<TbOrderInfo>(0);

    public TbOrderStatus() {
    }

    public TbOrderStatus(String osTitle, String osStatus, Set<TbOrderInfo> tbOrderInfos) {
       this.osTitle = osTitle;
       this.osStatus = osStatus;
       this.tbOrderInfos = tbOrderInfos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="os_id", unique=true, nullable=false)
    public Integer getOsId() {
        return this.osId;
    }
    
    public void setOsId(Integer osId) {
        this.osId = osId;
    }

    
    @Column(name="os_title", length=100)
    public String getOsTitle() {
        return this.osTitle;
    }
    
    public void setOsTitle(String osTitle) {
        this.osTitle = osTitle;
    }

    
    @Column(name="os_status", length=45)
    public String getOsStatus() {
        return this.osStatus;
    }
    
    public void setOsStatus(String osStatus) {
        this.osStatus = osStatus;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tbOrderStatus")
    public Set<TbOrderInfo> getTbOrderInfos() {
        return this.tbOrderInfos;
    }
    
    public void setTbOrderInfos(Set<TbOrderInfo> tbOrderInfos) {
        this.tbOrderInfos = tbOrderInfos;
    }




}


