package db_mapping_files;
// Generated Feb 23, 2018 2:08:47 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TbOrderInfo generated by hbm2java
 */
@Entity
@Table(name="tb_order_info"
    ,catalog="safenets_epacs"
)
public class TbOrderInfo  implements java.io.Serializable {


     private Integer oiId;
     private TbOrderStatus tbOrderStatus;
     private String oiGenId;
     private String oiDate;
     private String oiDiliveryDate;
     private String oiShippingDate;
     private String oiStatus;
     private Set<TbInvoiceInfo> tbInvoiceInfos = new HashSet<TbInvoiceInfo>(0);

    public TbOrderInfo() {
    }

	
    public TbOrderInfo(TbOrderStatus tbOrderStatus) {
        this.tbOrderStatus = tbOrderStatus;
    }
    public TbOrderInfo(TbOrderStatus tbOrderStatus, String oiGenId, String oiDate, String oiDiliveryDate, String oiShippingDate, String oiStatus, Set<TbInvoiceInfo> tbInvoiceInfos) {
       this.tbOrderStatus = tbOrderStatus;
       this.oiGenId = oiGenId;
       this.oiDate = oiDate;
       this.oiDiliveryDate = oiDiliveryDate;
       this.oiShippingDate = oiShippingDate;
       this.oiStatus = oiStatus;
       this.tbInvoiceInfos = tbInvoiceInfos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="oi_id", unique=true, nullable=false)
    public Integer getOiId() {
        return this.oiId;
    }
    
    public void setOiId(Integer oiId) {
        this.oiId = oiId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="tb_order_status_os_id", nullable=false)
    public TbOrderStatus getTbOrderStatus() {
        return this.tbOrderStatus;
    }
    
    public void setTbOrderStatus(TbOrderStatus tbOrderStatus) {
        this.tbOrderStatus = tbOrderStatus;
    }

    
    @Column(name="oi_gen_id", length=45)
    public String getOiGenId() {
        return this.oiGenId;
    }
    
    public void setOiGenId(String oiGenId) {
        this.oiGenId = oiGenId;
    }

    
    @Column(name="oi_date", length=45)
    public String getOiDate() {
        return this.oiDate;
    }
    
    public void setOiDate(String oiDate) {
        this.oiDate = oiDate;
    }

    
    @Column(name="oi_dilivery_date", length=45)
    public String getOiDiliveryDate() {
        return this.oiDiliveryDate;
    }
    
    public void setOiDiliveryDate(String oiDiliveryDate) {
        this.oiDiliveryDate = oiDiliveryDate;
    }

    
    @Column(name="oi_shipping_date", length=45)
    public String getOiShippingDate() {
        return this.oiShippingDate;
    }
    
    public void setOiShippingDate(String oiShippingDate) {
        this.oiShippingDate = oiShippingDate;
    }

    
    @Column(name="oi_status", length=45)
    public String getOiStatus() {
        return this.oiStatus;
    }
    
    public void setOiStatus(String oiStatus) {
        this.oiStatus = oiStatus;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tbOrderInfo")
    public Set<TbInvoiceInfo> getTbInvoiceInfos() {
        return this.tbInvoiceInfos;
    }
    
    public void setTbInvoiceInfos(Set<TbInvoiceInfo> tbInvoiceInfos) {
        this.tbInvoiceInfos = tbInvoiceInfos;
    }




}


