package db_mapping_files;
// Generated Feb 20, 2018 3:38:57 PM by Hibernate Tools 4.3.1



/**
 * TbPageAuthenticationHasTbFuntionAuthentication generated by hbm2java
 */
public class TbPageAuthenticationHasTbFuntionAuthentication  implements java.io.Serializable {


     private Integer pafaId;
     private TbFuntionAuthentication tbFuntionAuthentication;
     private TbUserRole tbUserRole;
     private String pafaStatus;

    public TbPageAuthenticationHasTbFuntionAuthentication() {
    }

	
    public TbPageAuthenticationHasTbFuntionAuthentication(TbFuntionAuthentication tbFuntionAuthentication, TbUserRole tbUserRole) {
        this.tbFuntionAuthentication = tbFuntionAuthentication;
        this.tbUserRole = tbUserRole;
    }
    public TbPageAuthenticationHasTbFuntionAuthentication(TbFuntionAuthentication tbFuntionAuthentication, TbUserRole tbUserRole, String pafaStatus) {
       this.tbFuntionAuthentication = tbFuntionAuthentication;
       this.tbUserRole = tbUserRole;
       this.pafaStatus = pafaStatus;
    }
   
    public Integer getPafaId() {
        return this.pafaId;
    }
    
    public void setPafaId(Integer pafaId) {
        this.pafaId = pafaId;
    }
    public TbFuntionAuthentication getTbFuntionAuthentication() {
        return this.tbFuntionAuthentication;
    }
    
    public void setTbFuntionAuthentication(TbFuntionAuthentication tbFuntionAuthentication) {
        this.tbFuntionAuthentication = tbFuntionAuthentication;
    }
    public TbUserRole getTbUserRole() {
        return this.tbUserRole;
    }
    
    public void setTbUserRole(TbUserRole tbUserRole) {
        this.tbUserRole = tbUserRole;
    }
    public String getPafaStatus() {
        return this.pafaStatus;
    }
    
    public void setPafaStatus(String pafaStatus) {
        this.pafaStatus = pafaStatus;
    }




}


