package db_mapping_files;
// Generated Feb 23, 2018 2:08:47 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TbProductInfo generated by hbm2java
 */
@Entity
@Table(name="tb_product_info"
    ,catalog="safenets_epacs"
)
public class TbProductInfo  implements java.io.Serializable {


     private Integer piId;
     private TbSubcatagoryInfo tbSubcatagoryInfo;
     private TbUserAccount tbUserAccount;
     private String piTitle;
     private String piJpTitle;
     private String piGenId;
     private String piDiscription;
     private String piJpDiscription;
     private String piInfo;
     private String piJpInfo;
     private Double piPrice;
     private String piStaus;
     private Set<TbImagesInfo> tbImagesInfos = new HashSet<TbImagesInfo>(0);
     private Set<TbCartInfo> tbCartInfos = new HashSet<TbCartInfo>(0);

    public TbProductInfo() {
    }

	
    public TbProductInfo(TbSubcatagoryInfo tbSubcatagoryInfo, TbUserAccount tbUserAccount) {
        this.tbSubcatagoryInfo = tbSubcatagoryInfo;
        this.tbUserAccount = tbUserAccount;
    }
    public TbProductInfo(TbSubcatagoryInfo tbSubcatagoryInfo, TbUserAccount tbUserAccount, String piTitle, String piJpTitle, String piGenId, String piDiscription, String piJpDiscription, String piInfo, String piJpInfo, Double piPrice, String piStaus, Set<TbImagesInfo> tbImagesInfos, Set<TbCartInfo> tbCartInfos) {
       this.tbSubcatagoryInfo = tbSubcatagoryInfo;
       this.tbUserAccount = tbUserAccount;
       this.piTitle = piTitle;
       this.piJpTitle = piJpTitle;
       this.piGenId = piGenId;
       this.piDiscription = piDiscription;
       this.piJpDiscription = piJpDiscription;
       this.piInfo = piInfo;
       this.piJpInfo = piJpInfo;
       this.piPrice = piPrice;
       this.piStaus = piStaus;
       this.tbImagesInfos = tbImagesInfos;
       this.tbCartInfos = tbCartInfos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="pi_id", unique=true, nullable=false)
    public Integer getPiId() {
        return this.piId;
    }
    
    public void setPiId(Integer piId) {
        this.piId = piId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="tb_subcatagory_info_si_id", nullable=false)
    public TbSubcatagoryInfo getTbSubcatagoryInfo() {
        return this.tbSubcatagoryInfo;
    }
    
    public void setTbSubcatagoryInfo(TbSubcatagoryInfo tbSubcatagoryInfo) {
        this.tbSubcatagoryInfo = tbSubcatagoryInfo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="tb_user_account_ua_id", nullable=false)
    public TbUserAccount getTbUserAccount() {
        return this.tbUserAccount;
    }
    
    public void setTbUserAccount(TbUserAccount tbUserAccount) {
        this.tbUserAccount = tbUserAccount;
    }

    
    @Column(name="pi_title", length=200)
    public String getPiTitle() {
        return this.piTitle;
    }
    
    public void setPiTitle(String piTitle) {
        this.piTitle = piTitle;
    }

    
    @Column(name="pi_jp_title", length=200)
    public String getPiJpTitle() {
        return this.piJpTitle;
    }
    
    public void setPiJpTitle(String piJpTitle) {
        this.piJpTitle = piJpTitle;
    }

    
    @Column(name="pi_gen_id", length=100)
    public String getPiGenId() {
        return this.piGenId;
    }
    
    public void setPiGenId(String piGenId) {
        this.piGenId = piGenId;
    }

    
    @Column(name="pi_discription")
    public String getPiDiscription() {
        return this.piDiscription;
    }
    
    public void setPiDiscription(String piDiscription) {
        this.piDiscription = piDiscription;
    }

    
    @Column(name="pi_jp_discription")
    public String getPiJpDiscription() {
        return this.piJpDiscription;
    }
    
    public void setPiJpDiscription(String piJpDiscription) {
        this.piJpDiscription = piJpDiscription;
    }

    
    @Column(name="pi_info", length=250)
    public String getPiInfo() {
        return this.piInfo;
    }
    
    public void setPiInfo(String piInfo) {
        this.piInfo = piInfo;
    }

    
    @Column(name="pi_jp_info", length=250)
    public String getPiJpInfo() {
        return this.piJpInfo;
    }
    
    public void setPiJpInfo(String piJpInfo) {
        this.piJpInfo = piJpInfo;
    }

    
    @Column(name="pi_price", precision=22, scale=0)
    public Double getPiPrice() {
        return this.piPrice;
    }
    
    public void setPiPrice(Double piPrice) {
        this.piPrice = piPrice;
    }

    
    @Column(name="pi_staus", length=45)
    public String getPiStaus() {
        return this.piStaus;
    }
    
    public void setPiStaus(String piStaus) {
        this.piStaus = piStaus;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tbProductInfo")
    public Set<TbImagesInfo> getTbImagesInfos() {
        return this.tbImagesInfos;
    }
    
    public void setTbImagesInfos(Set<TbImagesInfo> tbImagesInfos) {
        this.tbImagesInfos = tbImagesInfos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tbProductInfo")
    public Set<TbCartInfo> getTbCartInfos() {
        return this.tbCartInfos;
    }
    
    public void setTbCartInfos(Set<TbCartInfo> tbCartInfos) {
        this.tbCartInfos = tbCartInfos;
    }




}


