package db_mapping_files;
// Generated Feb 23, 2018 2:08:47 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TbStockInfo generated by hbm2java
 */
@Entity
@Table(name="tb_stock_info"
    ,catalog="safenets_epacs"
)
public class TbStockInfo  implements java.io.Serializable {


     private Integer siId;
     private String siAvalibleQty;
     private String siSoldQty;
     private String si;

    public TbStockInfo() {
    }

    public TbStockInfo(String siAvalibleQty, String siSoldQty, String si) {
       this.siAvalibleQty = siAvalibleQty;
       this.siSoldQty = siSoldQty;
       this.si = si;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="si_id", unique=true, nullable=false)
    public Integer getSiId() {
        return this.siId;
    }
    
    public void setSiId(Integer siId) {
        this.siId = siId;
    }

    
    @Column(name="si_avalible_qty", length=45)
    public String getSiAvalibleQty() {
        return this.siAvalibleQty;
    }
    
    public void setSiAvalibleQty(String siAvalibleQty) {
        this.siAvalibleQty = siAvalibleQty;
    }

    
    @Column(name="si_sold_qty", length=45)
    public String getSiSoldQty() {
        return this.siSoldQty;
    }
    
    public void setSiSoldQty(String siSoldQty) {
        this.siSoldQty = siSoldQty;
    }

    
    @Column(name="si_", length=45)
    public String getSi() {
        return this.si;
    }
    
    public void setSi(String si) {
        this.si = si;
    }




}


