package db_mapping_files;
// Generated Feb 21, 2018 1:25:15 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TbSubcatagoryInfo generated by hbm2java
 */
public class TbSubcatagoryInfo  implements java.io.Serializable {


     private Integer siId;
     private TbCatagoryInfo tbCatagoryInfo;
     private String siTitle;
     private String siStatus;
     private Set<TbProductInfo> tbProductInfos = new HashSet<TbProductInfo>(0);

    public TbSubcatagoryInfo() {
    }

	
    public TbSubcatagoryInfo(TbCatagoryInfo tbCatagoryInfo) {
        this.tbCatagoryInfo = tbCatagoryInfo;
    }
    public TbSubcatagoryInfo(TbCatagoryInfo tbCatagoryInfo, String siTitle, String siStatus, Set<TbProductInfo> tbProductInfos) {
       this.tbCatagoryInfo = tbCatagoryInfo;
       this.siTitle = siTitle;
       this.siStatus = siStatus;
       this.tbProductInfos = tbProductInfos;
    }
   
    public Integer getSiId() {
        return this.siId;
    }
    
    public void setSiId(Integer siId) {
        this.siId = siId;
    }
    public TbCatagoryInfo getTbCatagoryInfo() {
        return this.tbCatagoryInfo;
    }
    
    public void setTbCatagoryInfo(TbCatagoryInfo tbCatagoryInfo) {
        this.tbCatagoryInfo = tbCatagoryInfo;
    }
    public String getSiTitle() {
        return this.siTitle;
    }
    
    public void setSiTitle(String siTitle) {
        this.siTitle = siTitle;
    }
    public String getSiStatus() {
        return this.siStatus;
    }
    
    public void setSiStatus(String siStatus) {
        this.siStatus = siStatus;
    }
    public Set<TbProductInfo> getTbProductInfos() {
        return this.tbProductInfos;
    }
    
    public void setTbProductInfos(Set<TbProductInfo> tbProductInfos) {
        this.tbProductInfos = tbProductInfos;
    }




}


