package db_mapping_files;
// Generated Feb 21, 2018 1:25:15 AM by Hibernate Tools 4.3.1



/**
 * TbUserLog generated by hbm2java
 */
public class TbUserLog  implements java.io.Serializable {


     private Integer ulId;
     private TbUserAccount tbUserAccount;
     private String ulTime;
     private String ulIpAddress;
     private String ulStatus;
     private String ulDiscription;

    public TbUserLog() {
    }

	
    public TbUserLog(TbUserAccount tbUserAccount) {
        this.tbUserAccount = tbUserAccount;
    }
    public TbUserLog(TbUserAccount tbUserAccount, String ulTime, String ulIpAddress, String ulStatus, String ulDiscription) {
       this.tbUserAccount = tbUserAccount;
       this.ulTime = ulTime;
       this.ulIpAddress = ulIpAddress;
       this.ulStatus = ulStatus;
       this.ulDiscription = ulDiscription;
    }
   
    public Integer getUlId() {
        return this.ulId;
    }
    
    public void setUlId(Integer ulId) {
        this.ulId = ulId;
    }
    public TbUserAccount getTbUserAccount() {
        return this.tbUserAccount;
    }
    
    public void setTbUserAccount(TbUserAccount tbUserAccount) {
        this.tbUserAccount = tbUserAccount;
    }
    public String getUlTime() {
        return this.ulTime;
    }
    
    public void setUlTime(String ulTime) {
        this.ulTime = ulTime;
    }
    public String getUlIpAddress() {
        return this.ulIpAddress;
    }
    
    public void setUlIpAddress(String ulIpAddress) {
        this.ulIpAddress = ulIpAddress;
    }
    public String getUlStatus() {
        return this.ulStatus;
    }
    
    public void setUlStatus(String ulStatus) {
        this.ulStatus = ulStatus;
    }
    public String getUlDiscription() {
        return this.ulDiscription;
    }
    
    public void setUlDiscription(String ulDiscription) {
        this.ulDiscription = ulDiscription;
    }




}


