package db_mapping_files;
// Generated Feb 21, 2018 1:25:15 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TbUserRole generated by hbm2java
 */
public class TbUserRole  implements java.io.Serializable {


     private Integer urId;
     private String urTitile;
     private String urStatus;
     private Set<TbUserRoleHasTbPageAuthentication> tbUserRoleHasTbPageAuthentications = new HashSet<TbUserRoleHasTbPageAuthentication>(0);
     private Set<TbUserAccountHasTbUserRole> tbUserAccountHasTbUserRoles = new HashSet<TbUserAccountHasTbUserRole>(0);
     private Set<TbPageAuthenticationHasTbFuntionAuthentication> tbPageAuthenticationHasTbFuntionAuthentications = new HashSet<TbPageAuthenticationHasTbFuntionAuthentication>(0);

    public TbUserRole() {
    }

    public TbUserRole(String urTitile, String urStatus, Set<TbUserRoleHasTbPageAuthentication> tbUserRoleHasTbPageAuthentications, Set<TbUserAccountHasTbUserRole> tbUserAccountHasTbUserRoles, Set<TbPageAuthenticationHasTbFuntionAuthentication> tbPageAuthenticationHasTbFuntionAuthentications) {
       this.urTitile = urTitile;
       this.urStatus = urStatus;
       this.tbUserRoleHasTbPageAuthentications = tbUserRoleHasTbPageAuthentications;
       this.tbUserAccountHasTbUserRoles = tbUserAccountHasTbUserRoles;
       this.tbPageAuthenticationHasTbFuntionAuthentications = tbPageAuthenticationHasTbFuntionAuthentications;
    }
   
    public Integer getUrId() {
        return this.urId;
    }
    
    public void setUrId(Integer urId) {
        this.urId = urId;
    }
    public String getUrTitile() {
        return this.urTitile;
    }
    
    public void setUrTitile(String urTitile) {
        this.urTitile = urTitile;
    }
    public String getUrStatus() {
        return this.urStatus;
    }
    
    public void setUrStatus(String urStatus) {
        this.urStatus = urStatus;
    }
    public Set<TbUserRoleHasTbPageAuthentication> getTbUserRoleHasTbPageAuthentications() {
        return this.tbUserRoleHasTbPageAuthentications;
    }
    
    public void setTbUserRoleHasTbPageAuthentications(Set<TbUserRoleHasTbPageAuthentication> tbUserRoleHasTbPageAuthentications) {
        this.tbUserRoleHasTbPageAuthentications = tbUserRoleHasTbPageAuthentications;
    }
    public Set<TbUserAccountHasTbUserRole> getTbUserAccountHasTbUserRoles() {
        return this.tbUserAccountHasTbUserRoles;
    }
    
    public void setTbUserAccountHasTbUserRoles(Set<TbUserAccountHasTbUserRole> tbUserAccountHasTbUserRoles) {
        this.tbUserAccountHasTbUserRoles = tbUserAccountHasTbUserRoles;
    }
    public Set<TbPageAuthenticationHasTbFuntionAuthentication> getTbPageAuthenticationHasTbFuntionAuthentications() {
        return this.tbPageAuthenticationHasTbFuntionAuthentications;
    }
    
    public void setTbPageAuthenticationHasTbFuntionAuthentications(Set<TbPageAuthenticationHasTbFuntionAuthentication> tbPageAuthenticationHasTbFuntionAuthentications) {
        this.tbPageAuthenticationHasTbFuntionAuthentications = tbPageAuthenticationHasTbFuntionAuthentications;
    }




}


