package db_mapping_files;
// Generated Feb 21, 2018 1:25:15 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TbUserAccount generated by hbm2java
 */
public class TbUserAccount  implements java.io.Serializable {


     private Integer uaId;
     private String uaEmail;
     private String uaPassword;
     private String uaPin;
     private Date uaCreateTime;
     private String uaStatus;
     private Set<TbContactInfo> tbContactInfos = new HashSet<TbContactInfo>(0);
     private Set<TbUserAccountHasTbUserRole> tbUserAccountHasTbUserRoles = new HashSet<TbUserAccountHasTbUserRole>(0);
     private Set<TbProductInfo> tbProductInfos = new HashSet<TbProductInfo>(0);
     private Set<TbBasicInfo> tbBasicInfos = new HashSet<TbBasicInfo>(0);
     private Set<TbUserLog> tbUserLogs = new HashSet<TbUserLog>(0);

    public TbUserAccount() {
    }

    public TbUserAccount(String uaEmail, String uaPassword, String uaPin, Date uaCreateTime, String uaStatus, Set<TbContactInfo> tbContactInfos, Set<TbUserAccountHasTbUserRole> tbUserAccountHasTbUserRoles, Set<TbProductInfo> tbProductInfos, Set<TbBasicInfo> tbBasicInfos, Set<TbUserLog> tbUserLogs) {
       this.uaEmail = uaEmail;
       this.uaPassword = uaPassword;
       this.uaPin = uaPin;
       this.uaCreateTime = uaCreateTime;
       this.uaStatus = uaStatus;
       this.tbContactInfos = tbContactInfos;
       this.tbUserAccountHasTbUserRoles = tbUserAccountHasTbUserRoles;
       this.tbProductInfos = tbProductInfos;
       this.tbBasicInfos = tbBasicInfos;
       this.tbUserLogs = tbUserLogs;
    }
   
    public Integer getUaId() {
        return this.uaId;
    }
    
    public void setUaId(Integer uaId) {
        this.uaId = uaId;
    }
    public String getUaEmail() {
        return this.uaEmail;
    }
    
    public void setUaEmail(String uaEmail) {
        this.uaEmail = uaEmail;
    }
    public String getUaPassword() {
        return this.uaPassword;
    }
    
    public void setUaPassword(String uaPassword) {
        this.uaPassword = uaPassword;
    }
    public String getUaPin() {
        return this.uaPin;
    }
    
    public void setUaPin(String uaPin) {
        this.uaPin = uaPin;
    }
    public Date getUaCreateTime() {
        return this.uaCreateTime;
    }
    
    public void setUaCreateTime(Date uaCreateTime) {
        this.uaCreateTime = uaCreateTime;
    }
    public String getUaStatus() {
        return this.uaStatus;
    }
    
    public void setUaStatus(String uaStatus) {
        this.uaStatus = uaStatus;
    }
    public Set<TbContactInfo> getTbContactInfos() {
        return this.tbContactInfos;
    }
    
    public void setTbContactInfos(Set<TbContactInfo> tbContactInfos) {
        this.tbContactInfos = tbContactInfos;
    }
    public Set<TbUserAccountHasTbUserRole> getTbUserAccountHasTbUserRoles() {
        return this.tbUserAccountHasTbUserRoles;
    }
    
    public void setTbUserAccountHasTbUserRoles(Set<TbUserAccountHasTbUserRole> tbUserAccountHasTbUserRoles) {
        this.tbUserAccountHasTbUserRoles = tbUserAccountHasTbUserRoles;
    }
    public Set<TbProductInfo> getTbProductInfos() {
        return this.tbProductInfos;
    }
    
    public void setTbProductInfos(Set<TbProductInfo> tbProductInfos) {
        this.tbProductInfos = tbProductInfos;
    }
    public Set<TbBasicInfo> getTbBasicInfos() {
        return this.tbBasicInfos;
    }
    
    public void setTbBasicInfos(Set<TbBasicInfo> tbBasicInfos) {
        this.tbBasicInfos = tbBasicInfos;
    }
    public Set<TbUserLog> getTbUserLogs() {
        return this.tbUserLogs;
    }
    
    public void setTbUserLogs(Set<TbUserLog> tbUserLogs) {
        this.tbUserLogs = tbUserLogs;
    }




}


