package db_mapping_files;
// Generated Feb 20, 2018 3:38:57 PM by Hibernate Tools 4.3.1



/**
 * TbUserAccountHasTbUserRole generated by hbm2java
 */
public class TbUserAccountHasTbUserRole  implements java.io.Serializable {


     private Integer uaurId;
     private TbUserAccount tbUserAccount;
     private TbUserRole tbUserRole;
     private String uaurStatus;

    public TbUserAccountHasTbUserRole() {
    }

	
    public TbUserAccountHasTbUserRole(TbUserAccount tbUserAccount, TbUserRole tbUserRole) {
        this.tbUserAccount = tbUserAccount;
        this.tbUserRole = tbUserRole;
    }
    public TbUserAccountHasTbUserRole(TbUserAccount tbUserAccount, TbUserRole tbUserRole, String uaurStatus) {
       this.tbUserAccount = tbUserAccount;
       this.tbUserRole = tbUserRole;
       this.uaurStatus = uaurStatus;
    }
   
    public Integer getUaurId() {
        return this.uaurId;
    }
    
    public void setUaurId(Integer uaurId) {
        this.uaurId = uaurId;
    }
    public TbUserAccount getTbUserAccount() {
        return this.tbUserAccount;
    }
    
    public void setTbUserAccount(TbUserAccount tbUserAccount) {
        this.tbUserAccount = tbUserAccount;
    }
    public TbUserRole getTbUserRole() {
        return this.tbUserRole;
    }
    
    public void setTbUserRole(TbUserRole tbUserRole) {
        this.tbUserRole = tbUserRole;
    }
    public String getUaurStatus() {
        return this.uaurStatus;
    }
    
    public void setUaurStatus(String uaurStatus) {
        this.uaurStatus = uaurStatus;
    }




}


